<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_datos-del-lugar',
		'title' => 'Datos del lugar',
		'fields' => array (
			array (
				'key' => 'field_53226a9903f87',
				'label' => 'Este lugar es parte de una plaza o zona más grande?',
				'name' => 'venue_parent',
				'type' => 'post_object',
				'instructions' => 'Seleccione el lugar donde se encuentra contenido. Ejem: La Isla, La gran plaza, Galerías Diana, etc.',
				'post_type' => array (
					0 => 'eaca_directory',
					1 => 'eaca_hoteles',
					2 => 'eaca_venues',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53226b3d03f89',
				'label' => 'Sucursales',
				'name' => 'venue_relatives',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'eaca_directory',
					1 => 'eaca_hoteles',
					2 => 'eaca_venues',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_53226a3f03f86',
				'label' => 'Lugares relacionados',
				'name' => 'venue_related',
				'type' => 'relationship',
				'instructions' => 'Seleccione los lugares cercanos o relacionados',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'eaca_directory',
					1 => 'eaca_hoteles',
					2 => 'eaca_venues',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_53226b0403f88',
				'label' => 'Administradores',
				'name' => 'venue_admins',
				'type' => 'user',
				'role' => array (
					0 => 'author',
				),
				'field_type' => 'multi_select',
				'allow_null' => 1,
			),
			array (
				'key' => 'field_53226508baf1f',
				'label' => 'Dirección',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53224d29bc2d5',
				'label' => 'Calle',
				'name' => 'venue_street',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Av. Costera Miguel Alemán 1',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53224d4dbc2d6',
				'label' => 'Colonia',
				'name' => 'venue_neighborhood',
				'type' => 'taxonomy',
				'taxonomy' => 'neighborhood',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53224e80bc2d7',
				'label' => 'Código Postal',
				'name' => 'venue_zipcode',
				'type' => 'taxonomy',
				'taxonomy' => 'zipcode',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53224e99bc2d8',
				'label' => 'Ciudad',
				'name' => 'venue_city',
				'type' => 'text',
				'default_value' => 'Acapulco',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53225154bc2d9',
				'label' => 'Estado',
				'name' => 'venue_state',
				'type' => 'text',
				'default_value' => 'Guerrero',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_532266ccbaf27',
				'label' => 'Ubicación geográfica',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_532266fabaf28',
				'label' => 'Ubicación geográfica',
				'name' => 'venue_map',
				'type' => 'google_map',
				'center_lat' => '16.856463',
				'center_lng' => '-99.856796',
				'zoom' => 14,
				'height' => 300,
			),
			array (
				'key' => 'field_53225173bc2da',
				'label' => 'Datos de contacto',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53225186bc2db',
				'label' => 'Teléfono',
				'name' => 'venue_phone1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '(744) 123 4567',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_532251a8bc2dc',
				'label' => 'Correo electrónico',
				'name' => 'venue_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => 'correo@dominio.com',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5322652dbaf20',
				'label' => 'Página Web',
				'name' => 'venue_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_532265b9baf21',
				'label' => 'Redes Sociales',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_532265debaf22',
				'label' => 'Twitter',
				'name' => 'venue_twitter',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '@usuario',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53226622baf23',
				'label' => 'Facebook',
				'name' => 'venue_facebook',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5322662ebaf24',
				'label' => 'FourSquare',
				'name' => 'venue_foursquare',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53226662baf25',
				'label' => 'Youtube',
				'name' => 'venue_youtube',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5322666dbaf26',
				'label' => 'TripAdvisor',
				'name' => 'venue_tripadvisor',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5322698984dbe',
				'label' => 'Flickr',
				'name' => 'venue_flickr',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'eaca_directory',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'eaca_hoteles',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'eaca_venues',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
				1 => 'slug',
				2 => 'author',
				3 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_eventos',
		'title' => 'Eventos',
		'fields' => array (
			array (
				'key' => 'field_532209d771878',
				'label' => 'Lugar del evento',
				'name' => 'event_venue',
				'type' => 'relationship',
				'instructions' => 'Lugar donde se lleva a cabo el evento',
				'required' => 1,
				'return_format' => 'object',
				'post_type' => array (
					0 => 'eaca_directory',
					1 => 'eaca_hoteles',
					2 => 'eaca_venues',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_53220a2471879',
				'label' => 'Fuente',
				'name' => 'event_source',
				'type' => 'text',
				'instructions' => 'Dirección electrónica de la página donde anuncian el evento',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53220a677187a',
				'label' => 'Venta de boletos',
				'name' => 'event_tickets_url',
				'type' => 'text',
				'instructions' => 'Dirección de la página donde se pueden comprar los boletos. Ejem: http://www.ticketmaster.com.mx/search?tm_link=tm_header_search&user_input=&q=wizard+of+wonders+forum+mundo+imperial',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53220cb5b6c74',
				'label' => 'Inicio del evento',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5322097471876',
				'label' => 'Fecha inicio',
				'name' => 'event_start_date',
				'type' => 'date_picker',
				'instructions' => 'Fecha en que inicia el evento',
				'required' => 1,
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53220bcbb6c72',
				'label' => 'Hora de inicio',
				'name' => 'event_start_time_hour',
				'type' => 'select',
				'instructions' => 'Hora de inicio',
				'choices' => array (
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					13 => 13,
					14 => 14,
					15 => 15,
					16 => 16,
					17 => 17,
					18 => 18,
					19 => 19,
					20 => 20,
					21 => 21,
					22 => 22,
					23 => 23,
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53220c70b6c73',
				'label' => 'Minutos',
				'name' => 'event_start_time_minutes',
				'type' => 'select',
				'choices' => array (
					0 => 0,
					5 => 5,
					10 => 10,
					15 => 15,
					20 => 20,
					25 => 25,
					30 => 30,
					35 => 35,
					40 => 40,
					45 => 45,
					50 => 50,
					55 => 55,
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53220df00452f',
				'label' => 'Fin del evento',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_532209a371877',
				'label' => 'Fecha de termino',
				'name' => 'event_end_date',
				'type' => 'date_picker',
				'instructions' => 'Fecha en que termina el evento',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53220e4004531',
				'label' => 'Hora de finalización',
				'name' => 'event_end_time_hour',
				'type' => 'select',
				'instructions' => 'Hora de finalización',
				'choices' => array (
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					13 => 13,
					14 => 14,
					15 => 15,
					16 => 16,
					17 => 17,
					18 => 18,
					19 => 19,
					20 => 20,
					21 => 21,
					22 => 22,
					23 => 23,
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53220e0904530',
				'label' => 'Minutos',
				'name' => 'event_end_time_minutes',
				'type' => 'select',
				'choices' => array (
					0 => 0,
					5 => 5,
					10 => 10,
					15 => 15,
					20 => 20,
					25 => 25,
					30 => 30,
					35 => 35,
					40 => 40,
					45 => 45,
					50 => 50,
					55 => 55,
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53220f9d35282',
				'label' => 'Ubicación',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53220ec435280',
				'label' => 'Dirección',
				'name' => 'event_address',
				'type' => 'textarea',
				'instructions' => 'Dirección de donde se desarrollará el evento',
				'default_value' => '',
				'placeholder' => 'Av. Costera Miguel Alemán 1, Fracc. Costa Azul',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_53220f4c35281',
				'label' => 'Mapa de ubicación',
				'name' => 'event_map',
				'type' => 'google_map',
				'instructions' => 'Seleccione la ubicación donde se desarrolla el evento',
				'center_lat' => '16.856463',
				'center_lng' => '-99.856796',
				'zoom' => 12,
				'height' => 300,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'eaca_events',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
				1 => 'slug',
				2 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}

